framework:
    secret: '%env(APP_SECRET)%'
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        utf8: true
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
    validation: { enable_annotations: true }
